name: Download and Train Model
on:
    schedule:
        - cron: "0 0 * * MON,WED,FRI"
    workflow_dispatch:
jobs:
    download-tune:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo content
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use the PAT instead of the default GITHUB_TOKEN
            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                # Install a specific version of uv.
                version: "0.5.1"
                enable-cache: true
                cache-dependency-glob: "uv.lock"
            - name: Setup python
              uses: actions/setup-python@v5
              with:
                python-version-file: "pyproject.toml"
                cache: 'pip'
            - name: Install the project
              run: uv sync --all-extras --dev
#            - name: Setup python
#              uses: actions/setup-python@v5
#              with:
#                python-version: '3.11.9'
#                cache: 'pip'
#            - name: Install dependencies
#              run: pip install -r requirements.txt
            - name: Make envfile
              uses: SpicyPizza/create-envfile@v2.0
              with:
                envkey_API_KEY: ${{ secrets.API_KEY }}
                file_name: .env
                fail_on_empty: false
                sort_keys: false
            - name: Run download
              run: uv run main.py download
#              run: python main.py download
            - name: Run training
              run: uv run main.py train
#              run: python main.py train
            - name: Make demo page
              run: uv run main.py predict --plot
#              run: python main.py predict --plot
            - name: Check for changes # create env variable indicating if any changes were made
              id: git-check
              run: |
                git config user.name 'github-actions'
                git config user.email 'github-actions@github.com'
                git add .
                git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV 
            - name: Commit and push if changes
              if: env.changes == 'true' # if changes made push new data to repo
              run: |
                git pull
                git commit -m "downloaded new data and trained model"
                git push
